dependencies:
- name: elasticsearch
  version: 1.16.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  tags:
    - install-elasticsearch
- name: mongodb-replicaset
  version: 3.8.4
  repository: https://kubernetes-charts.storage.googleapis.com/
  tags:
    - install-mongodb
