apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "spinnaker.fullname" . }}-service-settings
  labels:
{{ include "spinnaker.standard-labels" . | indent 4 }}
data:
  redis.yml: |-
{{ template "spinnaker.serviceSettings.redis" . }}
  gate.yml: |-
{{ template "spinnaker.serviceSettings.gate" . }}
  deck.yml: |-
{{ template "spinnaker.serviceSettings.deck" . }}
{{- range $service, $data := .Values.halyard.additionalServiceSettings -}}
  {{- if and $data (ne $service "redis") (ne $service "gate") (ne $service "deck") }}
  {{ $service }}.yml: |-
{{ toYaml $data | indent 4 }}
  {{- end }}
{{- end }}
